const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const elements = new Map();
const get = key => {
  if (!elements.has(key)) elements.set(key,{innerHTML:'',textContent:'',value:'',open:false,addEventListener(){},classList:{add(){},remove(){}},showModal(){this.open=true;},close(){this.open=false;}});
  return elements.get(key);
};
const ctx = vm.createContext({console,Intl,Date,Set,JSON,Object,Array,String,Number,RegExp,Promise,AbortController,
  document:{querySelector:get,addEventListener(){}},window:{addEventListener(){},scrollTo(){}},
  localStorage:{getItem(){return null;},setItem(){}},setInterval(){},setTimeout(){},clearTimeout(){}});
for(const name of ['app.js','modules.js']) {
  const source=fs.readFileSync(path.join(__dirname,'../dist',name),'utf8');
  assert.doesNotMatch(source,/<\/[a-z]+\s+[^>]+>/,'Closing HTML tags must not contain attributes');
  vm.runInContext(source,ctx);
}
const evaluate = code => vm.runInContext(code,ctx);
const activity = "{start:'2026-09-01',end:'2026-09-30'}";
assert.equal(evaluate(`activityStatus(${activity},Date.parse('2026-08-31T23:59:59+08:00'))`),'未开始');
assert.equal(evaluate(`activityStatus(${activity},Date.parse('2026-09-01T00:00:00+08:00'))`),'进行中');
assert.equal(evaluate(`activityStatus(${activity},Date.parse('2026-09-30T23:59:59+08:00'))`),'进行中');
assert.equal(evaluate(`activityStatus(${activity},Date.parse('2026-10-01T00:00:00+08:00'))`),'已结束');
assert.equal(evaluate("validDate('2026-02-30')"),false);
assert.equal(evaluate("validDate('2026-09-22')"),true);
assert.equal(evaluate("risk('保证收益，稳赚').length"),2);
assert.equal(evaluate("risk('具体以正式条款为准').length"),0);
assert.equal(evaluate("extractPaymentTerms('缴费期间调整为5年或10年')"),'5 年交、10 年交');
assert.equal(evaluate("extractPaymentTerms('本通知不含缴费期间','保持原值')"),'保持原值');
evaluate("state.drafts.c1={text:'旧草稿',version:1}; applyProduct({rule:'新规则',effective:today(),scope:'新客户',sourceType:'公司业务通知',source:'产品资料管理员录入',sourceStatus:'训练复核通过',reviewer:'资料管理员',reviewedAt:today(),changeReason:'规则调整'});");
assert.equal(evaluate('state.product.version'),2);
assert.equal(evaluate('state.product.history[0].rule'),'保障计划一可选趸交、3 年交或 5 年交；保障计划二可选趸交或 3 年交。10 年交、20 年交不属于本产品可选交费期间。');
assert.equal(evaluate('state.product.history[0].reviewer'),'按太保官网在办产品披露与公开条款核对');
assert.equal(evaluate('state.product.history[0].facts.category'),'年金保险（互联网）');
assert.equal(evaluate("productContext().includes('现金价值与退保')"),true);
assert.equal(evaluate("productContext().includes('太平洋人寿[2025]年金保险 119 号')"),true);
assert.equal(evaluate("productContext().includes('10 年交：本产品不可选')"),true);
assert.equal(evaluate("productContext().includes('现金流 IRR')"),true);
assert.equal(evaluate('isVerifiedProduct({sourceStatus:"官方公开资料已核验"})'),true);
assert.equal(evaluate('state.drafts.c1.version!==state.product.version'),true);
evaluate("state.product.pending={rule:'未来规则',effective:'2099-01-01',scope:'新客户',sourceType:'公司业务通知',source:'产品资料管理员录入',sourceStatus:'训练复核通过',reviewer:'资料管理员',reviewedAt:today(),changeReason:'未来调整'};activateScheduledProduct();");
assert.equal(evaluate('state.product.version'),2);
assert.equal(evaluate('state.product.pending.rule'),'未来规则');
evaluate("state.product.pending.effective=today();activateScheduledProduct();");
assert.equal(evaluate('state.product.version'),3);
assert.equal(evaluate('state.product.pending'),undefined);
assert.equal(evaluate("getReply(state.customers.find(c=>c.id==='c4')).includes('电子保单')"),true);
assert.equal(evaluate("getReply(state.customers.find(c=>c.id==='c5')).includes('不再给您发产品介绍')"),true);
assert.equal(evaluate('state.activities.length'),2);
const plan = evaluate("calculatePlan(parsePlanText('保单年度,当年保费,当年领取,年末现金价值,身故保险金\\n1,10000,0,7000,10000\\n2,10000,0,15000,20000\\n3,0,3000,21000,23000'))");
assert.equal(plan.rows.length,3);
assert.equal(plan.rows[2].cumulativePremium,20000);
assert.equal(plan.rows[2].cumulativeBenefit,3000);
assert.equal(plan.summary.breakEvenYear,3);
assert.equal(Number.isFinite(plan.summary.lastSurrenderIrr),true);
assert.equal(evaluate("parsePlanText(JSON.stringify({rows:[{policyYear:1,premium:1000,annualBenefit:0,cashValue:900,deathBenefit:1000}]}))[0].cashValue"),900);
assert.equal(evaluate("profileEditorHTML(state.customers[0]).includes('个人养老金资金账户')"),true);
assert.equal(evaluate("renderPlanner().includes('逐年现金流与 IRR')"),true);
evaluate("planExtraction={status:'review',customerId:'c1',sourceName:'计划书.png',page_count:2,mode:'vision-ocr',raw_text:'原文',candidates:[{page:2,confidence:.9,sourceText:'1 10000 0 7000 10000',exactColumnCount:true,year:1,premium:10000,benefit:0,cashValue:7000,deathBenefit:10000}]}" );
assert.equal(evaluate("extractionReviewHTML(state.customers[0]).includes('识别结果复核')"),true);
assert.equal(evaluate("extractionReviewHTML(state.customers[0]).includes('第 2 页 · 90%')"),true);
assert.equal(evaluate("extractionReviewHTML(state.customers[0]).includes('确认选中行并写入测算')"),true);
evaluate("planExtraction=null");
assert.equal(evaluate("missingPlanProfile(state.customers[0]).includes('保障计划')"),true);
assert.equal(evaluate("moneyLabel(0).includes('0')"),true);
assert.equal(evaluate("formatRate(-0.0000001)"),'0.00%');
evaluate("state.planBooks.c1={...calculatePlan(parsePlanText('保单年度,当年保费,当年领取,年末现金价值,身故保险金\\n1,10000,0,7000,10000')),confirmed:true,productVersion:state.product.version}");
assert.equal(evaluate("planRowsContext(state.customers[0],state.planBooks.c1).includes('1年=10000/0/7000/10000')"),true);
evaluate("state.learning[0].status='已沉淀'");
assert.equal(evaluate("confirmedExperienceContext(state.customers[1]).includes('人工确认经验')"),true);
assert.equal(evaluate("knownContext(state.customers[1]).includes('覆盖产品事实')"),true);
console.log('PASS — expiry boundaries, invalid dates, risk rules, version history, scheduled activation, purchased/complaint service routing.');
